# Generated by Django 4.0.3 on 2022-03-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avistamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=50)),
                ('lugar', models.CharField(max_length=50)),
                ('latitud', models.CharField(max_length=50)),
                ('longitud', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
                ('notas', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreComun', models.CharField(max_length=50)),
                ('nombreCientifico', models.CharField(max_length=50)),
                ('reino', models.CharField(max_length=50)),
                ('filo', models.CharField(max_length=50)),
                ('clase', models.CharField(max_length=50)),
                ('orden', models.CharField(max_length=50)),
                ('familia', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=50)),
                ('especie', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('lugar', models.CharField(max_length=50)),
            ],
        ),
    ]
