# Generated by Django 4.0.3 on 2022-03-23 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avistamiento',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.especie'),
        ),
        migrations.AlterField(
            model_name='avistamiento',
            name='lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.lugar'),
        ),
        migrations.AlterField(
            model_name='avistamiento',
            name='notas',
            field=models.CharField(max_length=200),
        ),
    ]
